services:
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mynetwork
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    networks:
      - mynetwork
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
    env_file:
      - ./backend/.env

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    networks:
      - mynetwork
    env_file:
      - ./backend/.env

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
    name: mysql_data_volume
  db_init:
    name: mysql_init_volume
