version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge
